stages:
  - build

include:
  - project: 'sgsinfra/gitlab-ci-template'
    ref: master
    file:
    - "/build/.build_common.yml"
    - "/build/.publish_common.yml"    

build-dev:
  stage: build
  extends:
      - .node18-build
  script:
      - npm i --cache node_modules
      - npm run build
      - ls -al .next
      - mv .next dist
  artifacts:
      name: '$CI_JOB_NAME-$CI_COMMIT_REF_NAME'
      when: on_success
      expire_in: 30 min
      paths:
          - dist

publish:
  stage: publish
  extends:
    - .publish_common
  variables:
    ENV: "dev"
    IMAGE_NAME: "innoco-page-creator"