stages:
  - publish

include:
  - project: 'sgsinfra/gitlab-ci-template'
    ref: master
    file:
    - "/build/.publish_common.yml"    

publish:
  stage: publish
  extends:
    - .publish_common
  variables:
    ENV: "dev"
    IMAGE_NAME: "innoco-page-creator"